import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <Link href="/">
            <a>
              <li>Home</li>
            </a>
          </Link>{" "}
          <Link href="/about">
            <a>
              <li>About</li>
            </a>
          </Link>{" "}
          <Link href="/blog">
            <a>
              <li>Blog</li>
            </a>
          </Link>{" "}
          <Link href="/contact">
            <a>
              <li>Contact</li>
            </a>
          </Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Hunting Coder</a>
        </h1>

        <div className={styles.imgwrap}>
          <Image
            className={styles.myImg}
            src="/homeImg.jpg"
            height={108}
            width={198}
          />
        </div>

        <p className={styles.description}>
          A blog for hunting coders by hunting coders
        </p>

        <h2>Popular Blogs</h2>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>How to learn Javascript in 2022?</h2>
            <p>JavaScript is a language used to design logic for the web</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>How to learn Javascript in 2022?</h2>
            <p>JavaScript is a language used to design logic for the web</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>How to learn Javascript in 2022?</h2>
            <p>JavaScript is a language used to design logic for the web</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>How to learn Javascript in 2022?</h2>
            <p>JavaScript is a language used to design logic for the web</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
