import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Hunting Coder</a>
        </h1>

        <p className={styles.description}>
        A blog for hunting coders by hunting coders
        </p>

        <h2>Popular Blogs</h2>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>How to learn Javascript in 2022?</h2>
            <p>JavaScript is a language used to design logic for the web</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>How to learn Javascript in 2022?</h2>
            <p>JavaScript is a language used to design logic for the web</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>How to learn Javascript in 2022?</h2>
            <p>JavaScript is a language used to design logic for the web</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>How to learn Javascript in 2022?</h2>
            <p>JavaScript is a language used to design logic for the web</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
